import { Student, Surah } from './types';

export const AUDIO_BASE_URL = "https://download.quranicaudio.com/quran/muhammad_siddiq_al-minshawi/"; 
export const SFX_SUCCESS = "https://assets.mixkit.co/active_storage/sfx/2000/2000-preview.mp3"; 
export const SFX_CLICK = "https://assets.mixkit.co/active_storage/sfx/2568/2568-preview.mp3"; 
export const SFX_MEMORIZED = "https://assets.mixkit.co/active_storage/sfx/1435/1435-preview.mp3"; 
export const SFX_NEGATIVE = "https://assets.mixkit.co/active_storage/sfx/2572/2572-preview.mp3"; 

export const QURAN_TEXT: Record<number, string> = {
  114: "قُلۡ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَٰهِ ٱلنَّاسِ ۝ مِن شَرِّ ٱلۡوَسۡوَاسِ ٱلۡخَنَّاسِ ۝ ٱلَّذِي يُوَسۡوِسُ فِي صُدُورِ ٱلنَّاسِ ۝ مِنَ ٱلۡجِنَّةِ وَٱلنَّاسِ",
  113: "قُلۡ أَعُوذُ بِرَبِّ ٱلۡفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِي ٱلۡعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
  112: "قُلۡ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمۡ يَلِدۡ وَلَمۡ يُولَدۡ ۝ وَلَمۡ يَكُن لَّهُۥ كُفُوًا أَحَدُۢ",
  111: "تَبَّتۡ يَدَآ أَبِي لَهَبٖ وَتَبَّ ۝ مَآ أَغۡنَىٰ عَنۡهُ مَالُهُۥ وَمَا كَسَبَ ۝ سَيَصۡلَىٰ نَارٗا ذَاتَ لَهَبٖ ۝ وَٱمۡرَأَتُهُۥ حَمَّالَةَ ٱلۡحَطَبِ ۝ فِي جِيدِهَا حَبۡلٞ مِّن مَّسَدِۢ",
  110: "إِذَا جَآءَ نَصۡرُ ٱللَّهِ وَٱلۡفَتۡحُ ۝ وَرَأَيۡتَ ٱلنَّاسَ يَدۡخُلُونَ فِي دِينِ ٱللَّهِ أَفۡوَاجٗا ۝ فَسَبِّحۡ بِحَمۡدِ رَبِّكَ وَٱسۡتَغۡفِرۡهُۚ إِنَّهُۥ كَانَ تَوَّابَۢا",
  109: "قُلۡ يَٰٓأَيُّهَا ٱلۡكَٰفِرُونَ ۝ لَآ أَعۡبُدُ مَا تَعۡبُدُونَ ۝ وَلَآ أَنتُمۡ عَٰبِدُونَ مَآ أَعۡبُدُ ۝ وَلَآ أَنَا۠ عَابدٞ مَّا عَبَدتُّمۡ ۝ وَلَآ أَنتُمۡ عَٰبِدُونَ مَآ أَعۡبُدُ ۝ لَكُمۡ دِينُكُمۡ وَلِيَ دِينِ",
  108: "إِنَّآ أَعۡطَيۡنَٰكَ ٱلۡكَوۡثَرَ ۝ فَصَلِّ لِرَبِّكَ وَٱنۡحَرۡ ۝ إِنَّ شَانِئَكَ هُوَ ٱلۡأَبۡتَرُ",
  107: "أَرَءَيۡتَ ٱلَّذِي يُكَذِّبُ بِٱلدِّينِ ۝ فَذَٰلِكَ ٱلَّذِي يَدُعُّ ٱلۡيَتِيمَ ۝ وَلَا يَحُضُّ عَلَىٰ طَعَامِ ٱلۡمِسۡكِينِ ۝ فَوَيۡلٞ لِّلۡمُصَلِّينَ ۝ ٱلَّذِينَ هُمۡ عَن صَلَاتِهِمۡ سَاهُونَ ۝ ٱلَّذِينَ هُمۡ يُرَآءُونَ ۝ وَيَمۡنَعُونَ ٱلۡمَاعُونَ",
  106: "لِإِيلَٰفِ قُرَيۡشٍ ۝ إِۦلَٰفِهِمۡ رِحۡلَةَ ٱلشِّتَآءِ وَٱلصَّيۡفِ ۝ فَلۡيَعۡبُدُواْ رَبَّ هَٰذَا ٱلۡبَيۡتِ ۝ ٱلَّذِيٓ أَطۡعَمَهُم مِّن جُوعٖ وَءَامَنَهُم مِّنۡ خَوۡفِۢ",
  105: "أَلَمۡ تَرَ كَيۡفَ فَعَلَ رَبُّكَ بِأَصۡحَٰبِ ٱلۡفِيلِ ۝ أَلَمۡ يَجۡعَلۡ كَيۡدَهُمۡ فِي تَضۡلِيلٖ ۝ وَأَرۡسَلَ عَلَيۡهِمۡ طَيۡرًا أَبَابِيلَ ۝ تَرۡمِيهِم بِحِجَارَةٖ مِّن سِجِّيلٖ ۝ فَجَعَلَهُمۡ كَعَصۡفٖ مَّأۡكُولِۢ",
  104: "وَيۡلٞ لِّكُلِّ هُمَزَةٖ لُّمَزَةٍ ۝ ٱلَّذِي جَمَعَ مَالٗا وَعَدَّدَهُۥ ۝ يَحۡسَبُ أَنَّ مَالَهُۥٓ أَخۡلَدَهُۥ ۝ كَلَّاۖ لَيُنۢبَذَنَّ فِي ٱلۡحُطَمَةِ ۝ وَمَآ أَدۡرَىٰكَ مَا ٱلۡحُطَمَةُ ۝ نَارُ ٱللَّهِ ٱلۡمُوقَدَةُ ۝ ٱلَّتِي تَطَّلِعُ عَلَى ٱلۡأَفۡـِٔدَةِ ۝ إِنَّهَا عَلَيۡهِم مُّؤۡصَدَةٞ ۝ فِي عَمَدٖ مُّمَدَّدَةِۢ",
  103: "وَٱلۡعَصۡرِ ۝ إِنَّ ٱلۡإِنسَٰنَ لَفِي خُسۡرٍ ۝ إِلَّا ٱلَّذِينَ ءَامَنُواْ وَعَمِلُواْ ٱلصَّٰلِحَٰتِ وَتَوَاصَوۡاْ بِٱلۡحَقِّ وَتَوَاصَوۡاْ بِٱلصَّبۡرِ",
  102: "أَلۡهَىٰكُمُ ٱلتَّكَاثُرُ ۝ حَتَّىٰ زُرۡتُمُ ٱلۡمَقَابِرَ ۝ كَلَّا سَوۡفَ تَعۡلَمُونَ ۝ ثُمَّ كَلَّا سَوۡفَ تَعۡلَمُونَ ۝ كَلَّا لَوۡ تَعۡلَمُونَ عِلۡمَ ٱلۡيَقِينِ ۝ لَتَرَوُنَّ ٱلۡجَحِيمَ ۝ ثُمَّ لَتَرَوُنَّهَا عَيۡنَ ٱلۡيَقِينِ ۝ ثُمَّ لَتُسۡـَٔلُنَّ يَوۡمَئِذٍ عَنِ ٱلنَّعِيمِ",
  101: "ٱلۡقَارِعَةُ ۝ مَا ٱلۡقَارِعَةُ ۝ وَمَآ أَدۡرَىٰكَ مَا ٱلۡقَارِعَةُ ۝ يَوۡمَ يَكُونُ ٱلنَّاسُ كَٱلۡفَرَاشِ ٱلۡمَبۡثُوثِ ۝ وَتَكُونُ ٱلۡجِبَالُ كَٱلۡعِهِنِ ٱلۡمَنفُوشِ ۝ فَأَمَّا مَن ثَقُلَتۡ مَوَٰزِينُهُۥ ۝ فَهُوَ فِي عِيشَةٖ رَّاضِيَةٖ ۝ وَأَمَّا مَن خَفَّتۡ مَوَٰزِينُهُۥ ۝ فَأُمُّهُۥ هَاوِيَةٞ ۝ وَمَآ أَدۡرَىٰكَ مَا هِيَهۡ ۝ نَارٌ حَامِيَةُۢ",
  100: "وَٱلۡعَٰدِيَٰتِ ضَبۡحٗا ۝ فَٱلۡمُورِيَٰتِ قَدۡحٗا ۝ فَٱلۡمُغِيرَٰتِ صُبۡحٗا ۝ فَأَثَرۡنَ بِهِۦ نَقۡعٗا ۝ فَوَسَطۡنَ بِهِۦ جَمۡعًا ۝ إِنَّ ٱلۡإِنسَٰنَ لِرَبِّهِۦ لَكَنُودٞ ۝ وَإِنَّهُۥ عَلَىٰ ذَٰلِكَ لَشَهِيدٞ ۝ وَإِنَّهُۥ لِحُبِّ ٱلۡخَيۡرِ لَشَدِيدٌ ۝ ۞أَفَلَا يَعۡلَمُ إِذَا بُعۡثِرَ مَا فِي ٱلۡقُبُورِ ۝ وَحُصِّلَ مَا فِي ٱلصُّدُورِ ۝ إِنَّ رَبَّهُم بِهِمۡ يَوۡمَئِذٖ لَّخَبِيرُۢ",
  99: "إِذَا زُلۡزِلَتِ ٱلۡأَرۡضُ زِلۡزَالَهَا ۝ وَأَخۡرَجَتِ ٱلۡأَرۡضُ أَثۡقَالَهَا ۝ وَقَالَ ٱلۡإِنسَٰنُ مَا لَهَا ۝ يَوۡمَئِذٖ تُحَدِّثُ أَخۡبَارَهَا ۝ بِأَنَّ رَبَّكَ أَوۡحَىٰ لَهَا ۝ يَوۡمَئِذٖ يَصۡدُرُ ٱلنَّاسُ أَشۡتَاتٗا لِّيُرَوۡاْ أَعۡمَٰلَهُمۡ ۝ فَمَن يَعۡمَلۡ مِثۡقَالَ ذَرَّةٍ خَيۡرٗا يَرَهُۥ ۝ وَمَن يَعۡمَلۡ مِثۡقَالَ ذَرَّةٖ شَرّٗا يَرَهُۥ",
  98: "لَمۡ يَكُنِ ٱلَّذِينَ كَفَرُواْ مِنۡ أَهۡلِ ٱلۡكِتَٰبِ وَٱلۡمُشۡرِكِينَ مُنفَكِّينَ حَتَّىٰ تَأۡتِيَهُمُ ٱلۡبَيِّنَةُ ۝ رَسُولٞ مِّنَ ٱللَّهِ يَتۡلُواْ صُحُفٗا مُّطَهَّرَةٗ ۝ فِيهَا كُتُبٞ قَيِّمَةٞ...",
  97: "إِنَّآ أَنزَلۡنَٰهُ فِي لَيۡلَةِ ٱلۡقَدۡرِ ۝ وَمَآ أَدۡرَىٰكَ مَا لَيۡلَةُ ٱلۡقَدۡرِ ۝ لَيۡلَةُ ٱلۡقَدۡرِ خَيۡرٞ مِّنۡ أَلۡفِ شَهۡرٖ ۝ تَنَزَّلُ ٱلۡمَلَٰٓئِكَةُ وَٱلرُّوحُ فِيهَا بِإِذۡنِ رَبِّهِم مِّن كُلِّ أَمۡرٖ ۝ سَلَٰمٌ هِيَ حَتَّىٰ مَطۡلَعِ ٱلۡفَجۡرِ",
  78: "عَمَّ يَتَسَآءَلُونَ ۝ عَنِ ٱلنَّبَإِ ٱلۡعَظِيمِ ۝ ٱلَّذِي هُمۡ فِيهِ مُخۡتَلِفُونَ ۝ كَلَّا سَيَعۡلَمُونَ ۝ ثُمَّ كَلَّا سَيَعۡلَمُونَ...",
};

export const SURAHS: Surah[] = [
  { id: 114, name: "ناس", nameAr: "الناس", ayahs: 6 },
  { id: 113, name: "فلق", nameAr: "الفلق", ayahs: 5 },
  { id: 112, name: "اخلاص", nameAr: "الإخلاص", ayahs: 4 },
  { id: 111, name: "مسد", nameAr: "المسد", ayahs: 5 },
  { id: 110, name: "نصر", nameAr: "النصر", ayahs: 3 },
  { id: 109, name: "کافرون", nameAr: "الکافرون", ayahs: 6 },
  { id: 108, name: "کوثر", nameAr: "الکوثر", ayahs: 3 },
  { id: 107, name: "ماعون", nameAr: "الماعون", ayahs: 7 },
  { id: 106, name: "قریش", nameAr: "قریش", ayahs: 4 },
  { id: 105, name: "فیل", nameAr: "الفیل", ayahs: 5 },
  { id: 104, name: "همزه", nameAr: "الهمزة", ayahs: 9 },
  { id: 103, name: "عصر", nameAr: "العصر", ayahs: 3 },
  { id: 102, name: "تکاثر", nameAr: "التکاثر", ayahs: 8 },
  { id: 101, name: "قارعه", nameAr: "القارعة", ayahs: 11 },
  { id: 100, name: "عادیات", nameAr: "العادیات", ayahs: 11 },
  { id: 99, name: "زلزله", nameAr: "الزلزلة", ayahs: 8 },
  { id: 98, name: "بینه", nameAr: "البینة", ayahs: 8 },
  { id: 97, name: "قدر", nameAr: "القدر", ayahs: 5 },
  { id: 96, name: "علق", nameAr: "العلق", ayahs: 19 },
  { id: 95, name: "تین", nameAr: "التین", ayahs: 8 },
  { id: 94, name: "شرح", nameAr: "الشرح", ayahs: 8 },
  { id: 93, name: "ضحی", nameAr: "الضحی", ayahs: 11 },
  { id: 92, name: "لیل", nameAr: "اللیل", ayahs: 21 },
  { id: 91, name: "شمس", nameAr: "الشمس", ayahs: 15 },
  { id: 90, name: "بلد", nameAr: "البلد", ayahs: 20 },
  { id: 89, name: "فجر", nameAr: "الفجر", ayahs: 30 },
  { id: 88, name: "غاشیه", nameAr: "الغاشیة", ayahs: 26 },
  { id: 87, name: "اعلی", nameAr: "الأعلی", ayahs: 19 },
  { id: 86, name: "طارق", nameAr: "الطارق", ayahs: 17 },
  { id: 85, name: "بروج", nameAr: "البروج", ayahs: 22 },
  { id: 84, name: "انشقاق", nameAr: "الانشقاق", ayahs: 25 },
  { id: 83, name: "مطففین", nameAr: "المطففین", ayahs: 36 },
  { id: 82, name: "انفطار", nameAr: "الانفطار", ayahs: 19 },
  { id: 81, name: "تکویر", nameAr: "التکویر", ayahs: 29 },
  { id: 80, name: "عبس", nameAr: "عبس", ayahs: 42 },
  { id: 79, name: "نازعات", nameAr: "النازعات", ayahs: 46 },
  { id: 78, name: "نبأ", nameAr: "النبأ", ayahs: 40 }, 
];

export const INITIAL_STUDENTS: Student[] = [
  { id: 1, name: "کسری صوفی عبدالله", diamonds: 1, stars: 1, pluses: 2, note: "ماعون،قدر", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 2, name: "سید فرزام حسینی", diamonds: 1, stars: 2, pluses: 0, note: "قریش، روان بخون", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 3, name: "احسان برائی‌", diamonds: 1, stars: 1, pluses: 4, note: "عادیات‌", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 4, name: "احسان صالحی", diamonds: 0, stars: 2, pluses: 4, note: "قارعه", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 5, name: "اژوان صحت", diamonds: 1, stars: 1, pluses: 2, note: "قدر", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 6, name: "محمد قادری اقدم‌", diamonds: 0, stars: 3, pluses: 2, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 7, name: "آرمان صحت", diamonds: 1, stars: 2, pluses: 4, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 8, name: "پویا خسروی", diamonds: 0, stars: 1, pluses: 3, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 9, name: "ماردین افلاطونی", diamonds: 0, stars: 2, pluses: 3, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 10, name: "محمد شاه‌محمدی", diamonds: 0, stars: 0, pluses: 3, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 11, name: "آروین صوفی شریف", diamonds: 0, stars: 2, pluses: 2, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 12, name: "ماردین صوفی شریف", diamonds: 0, stars: 0, pluses: 3, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 13, name: "سهیل بهرامی", diamonds: 0, stars: 2, pluses: 4, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 14, name: "یاسین معروفی انور", diamonds: 0, stars: 0, pluses: 2, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 15, name: "کیان صوفی عبدالله", diamonds: 0, stars: 1, pluses: 2, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 16, name: "محمد امینی", diamonds: 0, stars: 0, pluses: 3, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 17, name: "محمد پریزادی", diamonds: 1, stars: 0, pluses: 0, note: "میدید", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 18, name: "ذکریا رسولی", diamonds: 1, stars: 1, pluses: 2, note: "قریش", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 19, name: "آریا شیخ جلیلی", diamonds: 1, stars: 1, pluses: 2, note: "اخلاص‌، قدر", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 20, name: "ماردین غفوریان", diamonds: 0, stars: 1, pluses: 3, note: "شلوغی ۲۴ آذر", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 21, name: "اتیلا‌ شکری", diamonds: 0, stars: 1, pluses: 0, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 22, name: "محمد خبیر", diamonds: 0, stars: 1, pluses: 4, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 23, name: "آرمان رنجبر", diamonds: 0, stars: 1, pluses: 1, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 24, name: "پوریا خسروی", diamonds: 0, stars: 1, pluses: 1, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 25, name: "ماهان امینی", diamonds: 0, stars: 1, pluses: 3, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 26, name: "سامی درخشان", diamonds: 0, stars: 1, pluses: 4, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 27, name: "هاوری شریفی", diamonds: 0, stars: 0, pluses: 3, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 28, name: "محمد فتحی", diamonds: 0, stars: 2, pluses: 1, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 29, name: "زانا‌ جوان‌پور", diamonds: 0, stars: 4, pluses: 1, note: "کلاس پنجم از اول", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 30, name: "مهیار صالحی", diamonds: 0, stars: 0, pluses: 2, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
  { id: 31, name: "ایمان خدادادی", diamonds: 0, stars: 1, pluses: 4, note: "", completedSurahs: [], ayahProgress: {}, memorizationProgress: {}, lastReview: {}, streak: 0 },
];